language: go
sudo: true

cache:
  directories:
    - $HOME/cache


addons: {apt: {packages: [yasm]}}


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libffi

before_script:
  - go get -v github.com/gonuts/dl

script:
  - make qtrt-

