language: go
sudo: true

go:
  - "1.9"
  - "1.10.x"
#  - master

addons: {apt: {packages: [yasm]}}

matrix:
  fast_finish: true
  include:
    # the actual compilin'
    - stage: Linux
      os: linux
      env: JOB=build-ubuntu14

before_install:

before_script:

script:  "./.travis/$JOB.sh"

